[setup.backends."0.0.0.0"]
description = "OpenWeatherMap API Server"
address = "0.0.0.0"
port = 8080

[setup.dictionaries."weather_auth".items.key]
description = "API token for openweathermap.org"
input_type = "string"
